---
- name: Install package to Debian
  become: true
  package:
    name: "{{ package_name}}"
    state: present
  when: ansible_os_family == "Debian"
  
- name: Install package to RedHat
  become: true
  yum:
    name: "{{ package_name}}"
    state: present
  when: ansible_os_family == "RedHat"
